version: '3.8'

services:
  kong-db:
    image: postgres:15
    container_name: kong-db
    environment:
      POSTGRES_USER: ${KONG_DB_USER}
      POSTGRES_DB: ${KONG_DB_NAME}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KONG_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
    depends_on:
      - kong-db
    networks:
      - kong-net

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"   # expose only if needed, and restrict by firewall
      # - "8444:8444"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  konga-db:
    image: postgres:11
    container_name: konga-db
    environment:
      POSTGRES_USER: ${KONGA_DB_USER}
      POSTGRES_DB: ${KONGA_DB_NAME}
      POSTGRES_PASSWORD: ${KONGA_DB_PASSWORD}
    volumes:
      - konga-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://${KONGA_DB_USER}:${KONGA_DB_PASSWORD}@konga-db:5432/${KONGA_DB_NAME}"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-db
      DB_PORT: 5432
      DB_USER: ${KONGA_DB_USER}
      DB_PASSWORD: ${KONGA_DB_PASSWORD}
      DB_DATABASE: ${KONGA_DB_NAME}
    depends_on:
      - konga-db
    networks:
      - kong-net

  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-db
      DB_PORT: 5432
      DB_USER: ${KONGA_DB_USER}
      DB_PASSWORD: ${KONGA_DB_PASSWORD}
      DB_DATABASE: ${KONGA_DB_NAME}
      NODE_ENV: production
    ports:
      - "1337:1337"
    depends_on:
      - konga-db
      - konga-prepare
      - kong
    networks:
      - kong-net

volumes:
  kong-db-data:
  konga-db-data:

networks:
  kong-net:
    driver: bridge